export const Constants = {
  SETUSER: 'SET_USER',
  SETPROJECTNAME: 'SET_PROJECT_NAME',
  SIGNIN: 'SIGN_IN',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILED: 'SIGNIN_FAILED',
  SIGNOUT: 'SIGN_OUT',
  VERIFY: 'VERIFY_USER',
  SETERROR: 'SET_ERROR',
};